service:
 name: rust-cognito-sync

plugins:
  - serverless-rust

provider:
  name: aws
  runtime: rust
  memorySize: 128
  stage: 'dev'
  region: ${self:custom.awsRegion, 'eu-central-1'} 
  timeout: 30
  logRetentionInDays: 3
  profile: ${self:custom.awsProfile, 'default'}
  


package:
  individually: true

functions:
    cognito_sync:
        handler: cognito-sync
        events:
          - http:
                method: get
                path: /



 